CREATE TABLE `lectureScripts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lectureId` int,
	`userId` int NOT NULL,
	`title` varchar(500) NOT NULL,
	`prompt` text NOT NULL,
	`category` enum('web3','ai','blockchain','defi','nft','metaverse','general') NOT NULL DEFAULT 'web3',
	`difficulty` enum('beginner','intermediate','advanced') NOT NULL DEFAULT 'beginner',
	`language` varchar(10) DEFAULT 'ko',
	`targetDurationMin` int DEFAULT 10,
	`scriptContent` text,
	`sections` text,
	`estimatedDurationSec` int DEFAULT 0,
	`sectionCount` int DEFAULT 0,
	`status` enum('generating','ready','error') NOT NULL DEFAULT 'generating',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lectureScripts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `productionPipelines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`scriptId` int NOT NULL,
	`title` varchar(500) NOT NULL,
	`status` enum('queued','script_gen','tts_gen','avatar_gen','compositing','completed','failed') NOT NULL DEFAULT 'queued',
	`progressPercent` int DEFAULT 0,
	`currentStep` varchar(255),
	`voiceProfileId` int,
	`voiceModProfileId` int,
	`faceSwapProfileId` int,
	`ttsVoiceId` varchar(128) DEFAULT 'alloy',
	`audioUrls` text,
	`avatarVideoUrls` text,
	`finalVideoUrl` text,
	`thumbnailUrl` text,
	`totalDurationSec` int DEFAULT 0,
	`errorMessage` text,
	`config` text,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `productionPipelines_id` PRIMARY KEY(`id`)
);
